# Generated by Django 5.2.14 on 2026-05-17 04:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager (L1)'), ('admin', 'Admin / HR')], default='employee', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('date_joined_org', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='goals.department')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('goal_setting', 'Phase 1 — Goal Setting'), ('q1', 'Q1 Check-in (July)'), ('q2', 'Q2 Check-in (October)'), ('q3', 'Q3 Check-in (January)'), ('q4', 'Q4 / Annual (March–April)')], max_length=20)),
                ('fiscal_year', models.CharField(help_text='e.g. 2025-26', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('phase', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='GoalSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('returned', 'Returned for Rework')], default='draft', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sheets', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_sheets', to='goals.goalcycle')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.PROTECT, related_name='goal_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uom', models.CharField(choices=[('numeric_min', 'Numeric — Higher is Better'), ('numeric_max', 'Numeric — Lower is Better'), ('pct_min', '% — Higher is Better'), ('pct_max', '% — Lower is Better'), ('timeline', 'Timeline (Date-based)'), ('zero', 'Zero-based (0 = Success)')], max_length=20)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_date', models.DateField(blank=True, help_text='Used when UoM is Timeline', null=True)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('10.00'), message='Minimum weightage is 10%.'), django.core.validators.MaxValueValidator(Decimal('100.00'), message='Maximum weightage per goal is 100%.')])),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('on_track', 'On Track'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_shared_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goals.goalsheet')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Sheet Submitted'), ('approve', 'Sheet Approved'), ('return', 'Sheet Returned'), ('lock', 'Sheet Locked'), ('unlock', 'Admin Unlocked Sheet'), ('edit_goal', 'Goal Edited'), ('edit_target', 'Target Edited'), ('edit_weightage', 'Weightage Edited'), ('achievement_update', 'Achievement Updated'), ('checkin', 'Manager Check-in Logged')], max_length=30)),
                ('field_changed', models.CharField(blank=True, max_length=80)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('extra_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='goals.goal')),
                ('goal_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='goals.goalsheet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SharedGoalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uom', models.CharField(choices=[('numeric_min', 'Numeric — Higher is Better'), ('numeric_max', 'Numeric — Lower is Better'), ('pct_min', '% — Higher is Better'), ('pct_max', '% — Lower is Better'), ('timeline', 'Timeline (Date-based)'), ('zero', 'Zero-based (0 = Success)')], max_length=20)),
                ('target', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric / % target (leave blank for Timeline/Zero)', max_digits=14, null=True)),
                ('target_date', models.DateField(blank=True, help_text='Deadline for Timeline UoM', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_templates', to='goals.goalcycle')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_templates', to='goals.department')),
                ('pushed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='shared_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_goals', to='goals.sharedgoaltemplate'),
        ),
        migrations.CreateModel(
            name='ThrustArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank for org-wide thrust areas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thrust_areas', to='goals.department')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.AddField(
            model_name='sharedgoaltemplate',
            name='thrust_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_templates', to='goals.thrustarea'),
        ),
        migrations.AddField(
            model_name='goal',
            name='thrust_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='goals.thrustarea'),
        ),
        migrations.CreateModel(
            name='ManagerCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Structured discussion notes from the check-in session')),
                ('is_complete', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to='goals.goalcycle')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.PROTECT, related_name='check_ins_received', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='check_ins_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_in_at'],
                'unique_together': {('employee', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlyAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric / % actual value', max_digits=14, null=True)),
                ('actual_date', models.DateField(blank=True, help_text='Completion date for Timeline goals', null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('on_track', 'On Track'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('computed_score', models.DecimalField(blank=True, decimal_places=4, help_text='Score 0–1 (100% = 1.0000). Tracking only, not rating.', max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='goals.goalcycle')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='goals.goal')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('goal', 'cycle')},
            },
        ),
    ]
