# Generated by Django 5.2.14 on 2026-05-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationrule',
            name='notify_employee_after',
            field=models.PositiveIntegerField(default=0, help_text='Days after threshold to notify employee'),
        ),
        migrations.AlterField(
            model_name='escalationrule',
            name='notify_hr_after',
            field=models.PositiveIntegerField(default=5, help_text='Days after manager notification to notify HR/skip-level'),
        ),
        migrations.AlterField(
            model_name='escalationrule',
            name='notify_manager_after',
            field=models.PositiveIntegerField(default=2, help_text='Days after employee notification to notify manager'),
        ),
    ]
